### ISSUE TITLE
希望能替换为别的字符

### ISSUE THREAD

**Issue by linonetwo** [ZhelinCheng/word-guard#204]
https://github.com/ZhelinCheng/mint-filter/blob/f25e00181977c729abd1eafd03d4077864edbb6f/src/index.ts#L91

星号看起来太严肃了，如果能自定义为❤或者黑框，就有赛博朋克或者基金会的感觉了

**Comment by ZhelinCheng** [comment]
const mint = new Mint(['拼多多', '多少'], { customCharacter: '❤' }); 这样就行

**Comment by linonetwo** [comment]
readme 里的链接需要更新了！https://github.com/ZhelinCheng/mint-filter/blob/f25e001/src/index.ts#L26

**Comment by linonetwo** [comment]
<img width="369" alt="截屏2023-07-13 13 10 11" src="https://github.com/ZhelinCheng/mint-filter/assets/3746270/7e150be8-6602-4d54-8e37-1d35b350420c">

SCP味来了
